apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kubevigil.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevigil.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubevigil.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubevigil.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "kubevigil.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
      {{- end }}
      hostPID: true
      hostNetwork: true
      {{- with .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config
            - /etc/kubevigil/config.yaml
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/kubevigil
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "kubevigil.fullname" . }}
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
